import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Promobar from "@/components/Promobar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fuel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Promobar/>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
