import { Inter } from "next/font/google";
import Script from "next/script";
import Head from 'next/head'; // Import Head component
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Head>
          <meta name="keywords" content="next, huntingcoder blog, hunting coder" />
        </Head>
        {children}
        <Script src="/sc.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
